name: BulwarkGitLeaks
on: [pull_request]

concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/spectro-dev-public/bulwark/gitleaks:latest
      env:
        REPO: ${{ github.event.repository.name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_CONFIG: config.toml
    steps:

      - name: run-bulwark-gitleaks-scan
        shell: sh
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          /workspace/bulwark \
            -area app \
            -component UI \
            -surface Code \
            -tool gitleaks \
            -target $REPO \
            -name CodeSASTGitLeaks \
            -tags "branch:$BRANCH" \
            -report html

      - name: check-result
        shell: sh
        run: |
          resultPath=./$REPO/gitleaks.html
          if [ -f "$resultPath" ]; then
            echo "GitLeaks report generated: $resultPath"
          else
            echo "GitLeaks report not found!"
            exit 1
          fi
