name: BulwarkGitLeaks
on: [pull_request]

concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/spectro-dev-public/bulwark/gitleaks:latest
      env:
        REPO: ${{ github.event.repository.name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_CONFIG: config.toml
    steps:

      - name: run-bulwark-gitleaks-scan
        shell: sh
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          # Run the scan and redirect all output to a known HTML file
          /workspace/bulwark \
            -area app \
            -component UI \
            -surface Code \
            -tool gitleaks \
            -target $REPO \
            -name CodeSASTGitLeaks \
            -tags "branch:$BRANCH" \
            -report html \
            > gitleaks_output.html 2>&1

      - name: check-result
        shell: sh
        run: |
          if [ -f "gitleaks_output.html" ]; then
            echo "GitLeaks report generated: gitleaks_output.html"
          else
            echo "GitLeaks report not found!"
            exit 1
          fi

      - name: Upload GitLeaks report artifact
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks_output.html
